version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
   volumes:
     - ./esdata:/usr/share/elasticsearch/data   
   container_name: elasticsearch
   ports:
     - "9200:9200"
   environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
     - ELASTIC_USERNAME=elastic
     - ELASTIC_PASSWORD=MagicWord
     - xpack.security.enabled=true
     
  kibana:
   image: docker.elastic.co/kibana/kibana:7.5.1
   container_name: kibana
   environment:
     - ELASTICSEARCH_USERNAME=elastic
     - ELASTICSEARCH_URL="http://elasticsearch:9200"
     - ELASTICSEARCH_PASSWORD=MagicWord
     - xpack.security.enabled=true
   links:
     - elasticsearch
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
    
volumes:
  esdata:    